# Generated by Django 5.2.8 on 2026-01-09 03:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name for the plan (e.g., "Premium", "Free")', max_length=50, unique=True, verbose_name='plan name')),
                ('tier', models.CharField(choices=[('FREE', 'Free'), ('PREMIUM', 'Premium')], default='FREE', help_text='Membership tier level', max_length=20, unique=True, verbose_name='tier')),
                ('price_monthly', models.DecimalField(decimal_places=2, default=0, help_text='Price in HKD per month', max_digits=10, verbose_name='monthly price')),
                ('daily_quiz_limit', models.PositiveIntegerField(default=5, help_text='Maximum quiz attempts per day (0 = unlimited)', verbose_name='daily quiz limit')),
                ('can_enter_competitions', models.BooleanField(default=False, help_text='Allow participation in competitions', verbose_name='can enter competitions')),
                ('has_progress_tracking', models.BooleanField(default=False, help_text='Enable detailed progress analytics', verbose_name='has progress tracking')),
                ('has_detailed_analytics', models.BooleanField(default=False, help_text='Enable detailed performance analytics', verbose_name='has detailed analytics')),
                ('has_certificates', models.BooleanField(default=False, help_text='Enable certificate generation', verbose_name='has certificates')),
                ('is_ad_free', models.BooleanField(default=False, help_text='Remove advertisements', verbose_name='ad-free experience')),
                ('access_all_questions', models.BooleanField(default=False, help_text='Access to all 100+ questions', verbose_name='access all questions')),
                ('description', models.TextField(blank=True, help_text='Short description of the plan', verbose_name='description')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this plan is available for new subscriptions', verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'subscription plan',
                'verbose_name_plural': 'subscription plans',
                'db_table': 'users_subscription_plan',
                'ordering': ['price_monthly'],
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled'), ('TRIAL', 'Trial')], default='ACTIVE', max_length=20, verbose_name='status')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, help_text='When the subscription started', verbose_name='start date')),
                ('end_date', models.DateTimeField(blank=True, help_text='When the subscription expires (null = indefinite)', null=True, verbose_name='end date')),
                ('payment_method', models.CharField(blank=True, help_text='e.g., "stripe", "paypal", "manual"', max_length=50, verbose_name='payment method')),
                ('transaction_id', models.CharField(blank=True, help_text='External payment transaction reference', max_length=255, verbose_name='transaction ID')),
                ('auto_renew', models.BooleanField(default=False, help_text='Automatically renew subscription', verbose_name='auto-renew')),
                ('cancelled_at', models.DateTimeField(blank=True, help_text='When the user cancelled the subscription', null=True, verbose_name='cancelled at')),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this subscription', verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='users.subscriptionplan', verbose_name='plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'user subscription',
                'verbose_name_plural': 'user subscriptions',
                'db_table': 'users_subscription',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='users_subsc_user_id_877733_idx'), models.Index(fields=['status', 'end_date'], name='users_subsc_status_7d6591_idx')],
            },
        ),
    ]
